repos:
    # MIT
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


    # MIT
-   repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
        -   id: commit-msg-regex-hook
            args: ["--pattern='Signed-off-by: .* <.*@.*\\..*>'",
                   "--failure_message='Ensure you are signing the DCO\n  Do this by adding -s to your commit: git commit -s -m <commit message>'"]
            stages: [commit-msg]


    # Apache 2.0
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        args: ["scan"]


    # MIT
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
        -   id: docker-compose-check

    #MyPy
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: docbot
        language: python  
        types: [python]
